### ISSUE TITLE
Crash when running "Start this AI"

### ISSUE THREAD

**Issue by a0981906660** [choephix/auto-gpt-webui#11]
Hi,

I am trying to deploy this project on my Raspberry Pi, but I encounter the following error when I click the "Start this AI" button.
The only left API key I didn't fill out is Pinecone. I followed [the instruction here](https://significant-gravitas.github.io/Auto-GPT/configuration/memory/) to set up a redis db instead. Unfortunately, it didn't work. Choosing `local` gives me the same error.

Any idea or suggestion?

```shell
rpi@rpi-desktop:~/repo/auto-gpt-webui$ npm start

> auto-gpt-webui@0.1.0 start
> turbo run start

• Packages in scope: backend, frontend
• Running start in 2 packages
• Remote caching disabled
frontend:start: cache miss, executing 2a1795e3b52f2e3e
backend:start: cache miss, executing 7b3180ab44e465aa
frontend:start:
frontend:start: > frontend@0.1.0 start
frontend:start: > vite --host 0.0.0.0
frontend:start:
backend:start:
backend:start: > backend@0.1.0 start
backend:start: > node server.js
backend:start:
backend:start: Server is running on port 2200
backend:start: Client connected, sending command log
frontend:start:
frontend:start:   VITE v4.2.1  ready in 3890 ms
frontend:start:
frontend:start:   ➜  Local:   http://localhost:7070/
frontend:start:   ➜  Network: http://192.168.31.100:7070/
frontend:start:   ➜  Network: http://10.172.3.69:7070/
frontend:start:   ➜  Network: http://172.17.0.1:7070/
backend:start: Client connected, sending command log
backend:start: Client connected, sending command log
backend:start: Received command: python scripts/main.py --gpt3only
backend:start: node:events:491
backend:start:       throw er; // Unhandled 'error' event
backend:start:       ^
backend:start:
backend:start: Error: write EPIPE
backend:start:     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
backend:start:     at writeGeneric (node:internal/stream_base_commons:151:3)
backend:start:     at Socket._writeGeneric (node:net:943:11)
backend:start:     at Socket._write (node:net:955:8)
backend:start:     at writeOrBuffer (node:internal/streams/writable:392:12)
backend:start:     at _write (node:internal/streams/writable:333:10)
backend:start:     at Writable.write (node:internal/streams/writable:337:10)
backend:start:     at /home/rpi/repo/auto-gpt-webui/apps/backend/server.js:195:33
backend:start:     at Layer.handle [as handle_request] (/home/rpi/repo/auto-gpt-webui/node_modules/express/lib/router/layer.js:95:5)
backend:start:     at next (/home/rpi/repo/auto-gpt-webui/node_modules/express/lib/router/route.js:144:13)
backend:start: Emitted 'error' event on Socket instance at:
backend:start:     at emitErrorNT (node:internal/streams/destroy:151:8)
backend:start:     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
backend:start:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
backend:start:   errno: -32,
backend:start:   code: 'EPIPE',
backend:start:   syscall: 'write'
backend:start: }
backend:start:
backend:start: Node.js v19.9.0
backend:start: npm ERR! Lifecycle script `start` failed with error:
backend:start: npm ERR! Error: command failed
backend:start: npm ERR!   in workspace: backend@0.1.0
backend:start: npm ERR!   at location: /home/rpi/repo/auto-gpt-webui/apps/backend
backend:start: ERROR: command finished with error: command (/home/rpi/repo/auto-gpt-webui/apps/backend) npm run start exited (1)
command (/home/rpi/repo/auto-gpt-webui/apps/backend) npm run start exited (1)

 Tasks:    0 successful, 2 total
Cached:    0 cached, 2 total
  Time:    1m7.818s

 ERROR  run failed: command  exited (1)
```

**Comment by a0981906660** [comment]
Just figured out how to fix this when no pinecone API key is available. Go to the `.env` file and delete the line:
`MEMORY_BACKEND=redis`
