### ISSUE TITLE
Start this Ai error

### ISSUE THREAD

**Issue by n01sf8** [choephix/auto-gpt-webui#8]
start: Error executing command: Command failed: python scripts/main.py
backend:start: Traceback (most recent call last):
backend:start:   File "C:\Users\danie\OneDrive\Desktop\AutoGPT\auto-gpt-webui\auto-gpt\scripts\main.py", line 3, in <module>
backend:start:     import commands as cmd
backend:start:   File "C:\Users\danie\OneDrive\Desktop\AutoGPT\auto-gpt-webui\auto-gpt\scripts\commands.py", line 1, in <module>
backend:start:     import browse
backend:start:   File "C:\Users\danie\OneDrive\Desktop\AutoGPT\auto-gpt-webui\auto-gpt\scripts\browse.py", line 1, in <module>
backend:start:     import requests
backend:start: ModuleNotFoundError: No module named 'requests'

**Comment by ItsAhadun** [comment]
The error message suggests that there is a missing module named "requests" which is required by the script "browse.py". The script "browse.py" is being imported by "commands.py", which in turn is being imported by "main.py".

To solve this error, you need to install the "requests" module using pip. You can do this by running the following command in your terminal:

`pip install requests`
